name:name: Repository Metrics

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  engagement-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📥 Install dependencies
        run: pip install requests

      - name: ✅ Send Telegram verification message
        run: |
          python -c "
import requests;
bot_token = '${{ secrets.BOT_TOKEN }}';
chat_id = '${{ secrets.CHAT_ID }}';
msg = '✅ StratX Bot is live. Engagement tracking running.';
requests.post(f'https://api.telegram.org/bot{bot_token}/sendMessage', params={'chat_id': chat_id, 'text': msg})
"

      - name: 📊 Run engagement tracking
        run: |
          mkdir -p logs
          python .github/metrics_pull.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PATTY: ${{ secrets.GITHUB_PAT }}